global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: resource-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - resource-service:8081
